### ISSUE TITLE
OpenMage 20.0.8 doesn't install from scratch - Missing file

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#1542]
I just downloaded the archive for OpenMage 20.0.8. When I try to access this version page in browser in order to initiate the installation I am getting the following error:

```
There was a problem proceeding with Magento installation.
Please contact developers with error messages on this page.

Warning: file_get_contents(/home/mydomain/public_html/openmage_2008/LICENSE.html): failed to open stream: No such file or directory  in /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Install/Block/Begin.php on line 68

#0 [internal function]: mageCoreErrorHandler(2, 'file_get_conten...', '/home/mydomain/p...', 68, Array)
#1 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Install/Block/Begin.php(68): file_get_contents('/home/mydomain/p...')
#2 /home/mydomain/public_html/openmage_2008/app/design/install/default/default/template/install/begin.phtml(40): Mage_Install_Block_Begin->getLicenseHtml()
#3 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Template.php(263): include('/home/mydomain/p...')
#4 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Template.php(294): Mage_Core_Block_Template->fetchView('install/default...')
#5 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Template.php(308): Mage_Core_Block_Template->renderView()
#6 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Abstract.php(938): Mage_Core_Block_Template->_toHtml()
#7 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Text/List.php(45): Mage_Core_Block_Abstract->toHtml()
#8 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Abstract.php(938): Mage_Core_Block_Text_List->_toHtml()
#9 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Abstract.php(656): Mage_Core_Block_Abstract->toHtml()
#10 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Abstract.php(600): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#11 /home/mydomain/public_html/openmage_2008/app/design/install/default/default/template/page.phtml(98): Mage_Core_Block_Abstract->getChildHtml('content')
#12 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Template.php(263): include('/home/mydomain/p...')
#13 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Template.php(294): Mage_Core_Block_Template->fetchView('install/default...')
#14 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Template.php(308): Mage_Core_Block_Template->renderView()
#15 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Block/Abstract.php(938): Mage_Core_Block_Template->_toHtml()
#16 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Model/Layout.php(590): Mage_Core_Block_Abstract->toHtml()
#17 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Controller/Varien/Action.php(406): Mage_Core_Model_Layout->getOutput()
#18 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Install/controllers/WizardController.php(120): Mage_Core_Controller_Varien_Action->renderLayout()
#19 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Install_WizardController->beginAction()
#20 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('begin')
#21 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#22 /home/mydomain/public_html/openmage_2008/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#23 /home/mydomain/public_html/openmage_2008/app/Mage.php(752): Mage_Core_Model_App->run(Array)
#24 /home/mydomain/public_html/openmage_2008/index.php(72): Mage::run('', 'store')
#25 {main}
```

The error reports a missing file named **LICENSE.html**. I put back this file from the last version which had it 20.0.6 and I got the installer page. 

**Both packages 20.0.7 and 20.0.8 do not have this file!**

**Comment by kiatng** [comment]
Reference of the `LICENSE.html` file

https://github.com/OpenMage/magento-lts/blob/28ecfb5f35a9c542910ecdb05a71552fe7cf8255/app/code/core/Mage/Install/Block/Begin.php#L61-L69

https://github.com/OpenMage/magento-lts/blob/28ecfb5f35a9c542910ecdb05a71552fe7cf8255/app/code/core/Mage/Install/etc/config.xml#L154
