### ISSUE TITLE
Reports - Products Reviews Error Page in OM 20.14

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#2237]
On a test server I have two identical installations based on the same Magento Sample 1.9. One is using OM-20.13 the other one OM-20.14. This instances are only for testing what is happening on every page in Frontend/Backend without touching the files. In general they help me to identify the issues that appeare between successive versions.

Now go to **Backend > Reports > Reviews > Product Reviews**. Here is what OM displays for each installation.

**This is OM-20.13**

![om_2013](https://user-images.githubusercontent.com/8360474/174499721-fdeb65cb-bc2b-44e1-936a-cb410f0fd86f.jpg)

**This is OM-20.14**

![om_2014](https://user-images.githubusercontent.com/8360474/174499734-77d7cd77-b2e7-42d5-bc78-bc85a5de35ab.jpg)

**Here is the report file content**

```
a:5:{i:0;s:650:"SELECT `e`.*, (SELECT COUNT(DISTINCT rev.review_id) FROM `review` AS `rev` WHERE (e.entity_id = rev.entity_pk_value)) AS `review_cnt`, MAX(r.created_at) AS `last_created`, `SUM(``table_rating``.``percent``)/COUNT(table_rating`.`rating_id)` AS `avg_rating`, `SUM(table_rating.percent_approved)/COUNT(table_rating`.`rating_id)` AS `avg_rating_approved` FROM `catalog_product_entity` AS `e`
 INNER JOIN `review` AS `r` ON e.entity_id = r.entity_pk_value
 LEFT JOIN `rating_option_vote_aggregated` AS `table_rating` ON e.entity_id = table_rating.entity_pk_value AND table_rating.store_id > 0 GROUP BY `e`.`entity_id` ORDER BY `review_cnt` DESC LIMIT 20

";i:1;s:5913:"#0 /home/mydomain/public_html/om_2014/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /home/mydomain/public_html/om_2014/lib/Zend/Db/Statement.php(303): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /home/mydomain/public_html/om_2014/lib/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /home/mydomain/public_html/om_2014/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `e`.*, (...', Array)
#4 /home/mydomain/public_html/om_2014/lib/Varien/Db/Adapter/Pdo/Mysql.php(508): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `e`.*, (...', Array)
#5 /home/mydomain/public_html/om_2014/lib/Zend/Db/Adapter/Abstract.php(739): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `e`.*, (...', Array)
#6 /home/mydomain/public_html/om_2014/lib/Varien/Data/Collection/Db.php(760): Zend_Db_Adapter_Abstract->fetchAll('SELECT `e`.*, (...', Array)
#7 /home/mydomain/public_html/om_2014/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(1067): Varien_Data_Collection_Db->_fetchAll('SELECT `e`.*, (...')
#8 /home/mydomain/public_html/om_2014/app/code/core/Mage/Eav/Model/Entity/Collection/Abstract.php(885): Mage_Eav_Model_Entity_Collection_Abstract->_loadEntities(false, false)
#9 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(553): Mage_Eav_Model_Entity_Collection_Abstract->load()
#10 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Report/Review/Product/Grid.php(52): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#11 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(646): Mage_Adminhtml_Block_Report_Review_Product_Grid->_prepareCollection()
#12 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(653): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#13 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(937): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#14 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(656): Mage_Core_Block_Abstract->toHtml()
#15 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(600): Mage_Core_Block_Abstract->_getChildHtml('grid', true)
#16 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Widget/Grid/Container.php(77): Mage_Core_Block_Abstract->getChildHtml('grid')
#17 /home/mydomain/public_html/om_2014/app/design/adminhtml/default/default/template/widget/grid/container.phtml(36): Mage_Adminhtml_Block_Widget_Grid_Container->getGridHtml()
#18 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Template.php(263): include('/home/mydomain/p...')
#19 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Template.php(294): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#20 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Template.php(308): Mage_Core_Block_Template->renderView()
#21 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#22 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Widget/Container.php(308): Mage_Adminhtml_Block_Template->_toHtml()
#23 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(938): Mage_Adminhtml_Block_Widget_Container->_toHtml()
#24 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Text/List.php(45): Mage_Core_Block_Abstract->toHtml()
#25 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(938): Mage_Core_Block_Text_List->_toHtml()
#26 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(656): Mage_Core_Block_Abstract->toHtml()
#27 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(600): Mage_Core_Block_Abstract->_getChildHtml('content', true)
#28 /home/mydomain/public_html/om_2014/app/design/adminhtml/default/default/template/page.phtml(74): Mage_Core_Block_Abstract->getChildHtml('content')
#29 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Template.php(263): include('/home/mydomain/p...')
#30 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Template.php(294): Mage_Core_Block_Template->fetchView('adminhtml/defau...')
#31 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Template.php(308): Mage_Core_Block_Template->renderView()
#32 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/Block/Template.php(81): Mage_Core_Block_Template->_toHtml()
#33 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Block/Abstract.php(938): Mage_Adminhtml_Block_Template->_toHtml()
#34 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Model/Layout.php(590): Mage_Core_Block_Abstract->toHtml()
#35 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Controller/Varien/Action.php(406): Mage_Core_Model_Layout->getOutput()
#36 /home/mydomain/public_html/om_2014/app/code/core/Mage/Adminhtml/controllers/Report/ReviewController.php(95): Mage_Core_Controller_Varien_Action->renderLayout()
#37 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Controller/Varien/Action.php(437): Mage_Adminhtml_Report_ReviewController->productAction()
#38 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(262): Mage_Core_Controller_Varien_Action->dispatch('product')
#39 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Controller/Varien/Front.php(192): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#40 /home/mydomain/public_html/om_2014/app/code/core/Mage/Core/Model/App.php(381): Mage_Core_Controller_Varien_Front->dispatch()
#41 /home/mydomain/public_html/om_2014/app/Mage.php(744): Mage_Core_Model_App->run(Array)
#42 /home/mydomain/public_html/om_2014/index.php(77): Mage::run('', 'store')
#43 {main}";s:3:"url";s:84:"/om_2014/index.php/admin/report_review/product/key/4c32250fd7c3381178ff556a3081cce0/";s:11:"script_name";s:18:"/om_2014/index.php";s:4:"skin";s:5:"admin";}
```

Please try to reproduce this issue with your installations. If it confirms we should find the PR that created the problem.

**Comment by tmotyl** [comment]
Whats the error message?

**Comment by ADDISON74** [comment]
@tmotyl - see above what is the report file.

**Comment by fballiano** [comment]
I tried to replicate on a vanilla installation and on a customer's website but I don't get this error.

the query in your report seems to have a lot of problems but it maybe because of the github copypaste formatting, the "quoting" is wrong in many places

**Comment by tmotyl** [comment]
@ADDISON74 usually there is also an exception message in the repory file which I dont see here

**Comment by ADDISON74** [comment]
@tmotyl - there are no files in /var/log directory.

The important thing is that I have feedback that does not confirm the issue. I will make a backup of this version. then I will use it in testing by reinstalling OM. if I do not get the desired result then I will identify the files responsible for the error.

**Comment by ADDISON74** [comment]
I will close this issue and if I have new information after detailed testing I will open it for discussion. 

Thank you both for testing.

**Comment by ADDISON74** [comment]
When I reported this issue I did not remember that some time ago I replaced **/app/code/core/Zend** with ZF1-Future,. For this reason the rest of you could not reproduce it, but in the meantime we switched to ZF1-Future and we have the proposal to delete two custom files (PR #2861). If these files are deleted then the error will be reproduced immediately.

**Comment by ADDISON74** [comment]
I am closing this issue. @fballiano did a great job and he posted a fix. I confirm it is working.
