### ISSUE TITLE
Can't retrieve entity config (after delete extension)

### ISSUE THREAD

**Issue by sreichel** [OpenMage/magento-lts#3175]
### Preconditions (*)

1. `main` branch, works on `v19`

Bug comes from #2993

### Steps to reproduce (*)

1. install an extension that has custom eav attributes
2. uninstall, but leave orphan db entries
3. open admin panel

### Expected result (*)

1. works

### Actual result (*)

1.
```
Can't retrieve entity config: ave_sizechart/eav_attribute

#0 /var/www/html/app/code/core/Mage/Core/Model/Resource.php(280): Mage::throwException('Can't retrieve ...')
#1 /var/www/html/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(269): Mage_Core_Model_Resource->getTableName('ave_sizechart/e...')
#2 /var/www/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(480): Mage_Core_Model_Resource_Db_Abstract->getTable('ave_sizechart/e...')
#3 /var/www/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(565): Mage_Core_Model_Resource_Db_Collection_Abstract->getTable('ave_sizechart/e...')
#4 /var/www/html/app/code/core/Mage/Eav/Model/Resource/Entity/Attribute/Collection.php(112): Mage_Core_Model_Resource_Db_Collection_Abstract->join('ave_sizechart/e...', 'additional_tabl...')
#5 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Type.php(110): Mage_Eav_Model_Resource_Entity_Attribute_Collection->setEntityTypeFilter(Object(Mage_Eav_Model_Entity_Type))
#6 /var/www/html/app/code/core/Mage/Eav/Model/Config.php(212): Mage_Eav_Model_Entity_Type->getAttributeCollection()
#7 /var/www/html/app/code/core/Mage/Eav/Model/Config.php(172): Mage_Eav_Model_Config->_loadEntityAttributes(Object(Mage_Eav_Model_Entity_Type), 0)
#8 /var/www/html/app/code/core/Mage/Eav/Model/Config.php(386): Mage_Eav_Model_Config->_initializeStore()
#9 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Abstract.php(267): Mage_Eav_Model_Config->getEntityType('customer')
#10 /var/www/html/app/code/core/Mage/Customer/Model/Resource/Customer.php(33): Mage_Eav_Model_Entity_Abstract->setType('customer')
#11 /var/www/html/app/code/core/Mage/Core/Model/Config.php(1447): Mage_Customer_Model_Resource_Customer->__construct(Array)
```

**Comment by sreichel** [comment]
> How do you uninstall the extension?

Just removed code. M1 never finished support for uninstalling modules ... so it very common that orphan DB entries remain, but this should not cause errors now.

**Comment by ADDISON74** [comment]
Now I understand. The error should not occur as long as you removed the configuration file from /app/etc/modules.

**Comment by davidhiendl** [comment]
@ADDISON74 This is caused by the `getTableName` function not finding the XML model-class name registration anymore when loading an attribute that does not exist. The reason it previously didn't raise an error is because entity types were lazy-loaded and now they aren't (all at once to reduce DB query & allow caching for performance).

Need to think about how to best mitigate this without introducing performance issues.

**Comment by davidhiendl** [comment]
I think I found a good way to mitigate this without introducing an issue by verifying that the module class is registered before attempting to load them and including non-existent ones. The only thing I'm concerned about is that it will be very hard to understand what's happening when a mistake was made when writing new attribute related classes. I might have to do something like error/log only if `Mage::isDeveloperMode`.

**Comment by fballiano** [comment]
@davidhiendl do you have news on this? I'm writing this just not to forget it :-)

**Comment by davidhiendl** [comment]
@fballiano I did not forget, but I've noticed some problems in production with my current solution.

**Comment by ADDISON74** [comment]
@davidhiendl - any updates to solve this issue?

**Comment by pquerner** [comment]
> @ADDISON74 This is caused by the `getTableName` function not finding the XML model-class name registration anymore when loading an attribute model class that (probably) does not exist anymore as well. The reason it previously didn't raise an error is because entity types were lazy-loaded and now they aren't (all at once to reduce DB query & allow caching for performance).
> 
> Need to think about how to best mitigate this without introducing performance issues.

Do you know which commit this was?

**Comment by davidhiendl** [comment]
I'm pretty sure it was squashed with my large EAV cache rewrite. I will submit the PR today.

**Comment by davidhiendl** [comment]
PR is available for testing. I decided to only focus on fixing the issue with entity types and keeping the old behavior where loading old attributes that had their implementation classes removed always caused an exception because I really dislike the idea of silently ignoring those.

**Comment by ADDISON74** [comment]
I confirm this issue. Just install an extension then delete all its files from the OM installation. If you reload the page a report file is generated

![report](https://github.com/OpenMage/magento-lts/assets/8360474/c3dc0422-e32c-4d13-b572-654f27425210)

The report file content is the same as Sven pointed in the issue description

```
a:5:{i:0;s:57:"Can't retrieve entity config: ave_sizechart/eav_attribute";i:1;s:6207:"#0 /var/www/html/app/code/core/Mage/Core/Model/Resource.php(273): Mage::throwException('Can't retrieve ...')
#1 /var/www/html/app/code/core/Mage/Core/Model/Resource/Db/Abstract.php(262): Mage_Core_Model_Resource->getTableName('ave_sizechart/e...')
#2 /var/www/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(473): Mage_Core_Model_Resource_Db_Abstract->getTable('ave_sizechart/e...')
#3 /var/www/html/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(558): Mage_Core_Model_Resource_Db_Collection_Abstract->getTable('ave_sizechart/e...')
#4 /var/www/html/app/code/core/Mage/Eav/Model/Resource/Entity/Attribute/Collection.php(103): Mage_Core_Model_Resource_Db_Collection_Abstract->join('ave_sizechart/e...', 'additional_tabl...')
#5 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Type.php(126): Mage_Eav_Model_Resource_Entity_Attribute_Collection->setEntityTypeFilter(Object(Mage_Eav_Model_Entity_Type))
#6 /var/www/html/app/code/core/Mage/Eav/Model/Config.php(205): Mage_Eav_Model_Entity_Type->newAttributeCollection()
#7 /var/www/html/app/code/core/Mage/Eav/Model/Config.php(165): Mage_Eav_Model_Config->_loadEntityAttributes(Object(Mage_Eav_Model_Entity_Type), 0)
#8 /var/www/html/app/code/core/Mage/Eav/Model/Config.php(379): Mage_Eav_Model_Config->_initializeStore()
#9 /var/www/html/app/code/core/Mage/Eav/Model/Entity/Abstract.php(260): Mage_Eav_Model_Config->getEntityType('catalog_product')
#10 /var/www/html/app/code/core/Mage/Catalog/Model/Resource/Product.php(44): Mage_Eav_Model_Entity_Abstract->setType('catalog_product')
#11 /var/www/html/app/code/core/Mage/Core/Model/Config.php(1440): Mage_Catalog_Model_Resource_Product->__construct(Array)
#12 /var/www/html/app/code/core/Mage/Core/Model/Config.php(1476): Mage_Core_Model_Config->getModelInstance('catalog_resourc...', Array)
#13 /var/www/html/app/Mage.php(552): Mage_Core_Model_Config->getResourceModelInstance('catalog/product', Array)
#14 /var/www/html/app/Mage.php(580): Mage::getResourceModel('catalog/product', Array)
#15 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(184): Mage::getResourceSingleton('catalog/product')
#16 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(200): Mage_Core_Model_Abstract->_getResource()
#17 /var/www/html/app/code/core/Mage/Core/Model/Abstract.php(213): Mage_Core_Model_Abstract->getIdFieldName()
#18 /var/www/html/lib/Varien/Data/Collection.php(387): Mage_Core_Model_Abstract->getId()
#19 /var/www/html/lib/Varien/Data/Collection/Db.php(162): Varien_Data_Collection->_getItemId(Object(Mage_Catalog_Model_Product))
#20 /var/www/html/lib/Varien/Data/Collection.php(354): Varien_Data_Collection_Db->_getItemId(Object(Mage_Catalog_Model_Product))
#21 /var/www/html/lib/Varien/Data/Collection/Db.php(584): Varien_Data_Collection->addItem(Object(Mage_Catalog_Model_Product))
#22 /var/www/html/app/code/core/Mage/Reports/Model/Resource/Report/Collection/Abstract.php(270): Varien_Data_Collection_Db->load(false, false)
#23 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(598): Mage_Reports_Model_Resource_Report_Collection_Abstract->load()
#24 /var/www/html/app/code/core/Mage/Adminhtml/Block/Dashboard/Tab/Products/Ordered.php(52): Mage_Adminhtml_Block_Widget_Grid->_prepareCollection()
#25 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(701): Mage_Adminhtml_Block_Dashboard_Tab_Products_Ordered->_prepareCollection()
#26 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Grid.php(712): Mage_Adminhtml_Block_Widget_Grid->_prepareGrid()
#27 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(925): Mage_Adminhtml_Block_Widget_Grid->_beforeToHtml()
#28 /var/www/html/app/code/core/Mage/Adminhtml/Block/Dashboard/Grids.php(51): Mage_Core_Block_Abstract->toHtml()
#29 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(299): Mage_Adminhtml_Block_Dashboard_Grids->_prepareLayout()
#30 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(474): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#31 /var/www/html/app/code/core/Mage/Adminhtml/Block/Dashboard.php(73): Mage_Core_Model_Layout->createBlock('adminhtml/dashb...')
#32 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(299): Mage_Adminhtml_Block_Dashboard->_prepareLayout()
#33 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(474): Mage_Core_Block_Abstract->setLayout(Object(Mage_Core_Model_Layout))
#34 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(490): Mage_Core_Model_Layout->createBlock('adminhtml/dashb...', 'dashboard')
#35 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(234): Mage_Core_Model_Layout->addBlock('adminhtml/dashb...', 'dashboard')
#36 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(200): Mage_Core_Model_Layout->_generateBlock(Object(Mage_Core_Model_Layout_Element), Object(Mage_Core_Model_Layout_Element))
#37 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(205): Mage_Core_Model_Layout->generateBlocks(Object(Mage_Core_Model_Layout_Element))
#38 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(345): Mage_Core_Model_Layout->generateBlocks()
#39 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(256): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#40 /var/www/html/app/code/core/Mage/Adminhtml/Controller/Action.php(293): Mage_Core_Controller_Varien_Action->loadLayout(NULL, true, true)
#41 /var/www/html/app/code/core/Mage/Adminhtml/controllers/DashboardController.php(34): Mage_Adminhtml_Controller_Action->loadLayout()
#42 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(421): Mage_Adminhtml_DashboardController->indexAction()
#43 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch('index')
#44 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(181): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#45 /var/www/html/app/code/core/Mage/Core/Model/App.php(358): Mage_Core_Controller_Varien_Front->dispatch()
#46 /var/www/html/app/Mage.php(740): Mage_Core_Model_App->run(Array)
#47 /var/www/html/index.php(56): Mage::run('', 'store')
#48 {main}";s:3:"url";s:70:"/index.php/admin/dashboard/index/key/e869e1411947e1393422a8699a3348de/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```
