### ISSUE TITLE
Can't create customer from backend.

### ISSUE THREAD

**Issue by TangLiang** [OpenMage/magento-lts#3264]
### PHP 8.2.4,OpenMage 20.1.0-rc3

**create customer from backend without Date Of Birth**
`````````````````````
[15-May-2023 16:19:57 UTC] PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - string in /home/wwwroot/lnmp01/domain/magentorc_05/web/vendor/shardj/zf1-future/library/Zend/Locale/Math/PhpMath.php:97
Stack trace:
#0 /home/wwwroot/lnmp01/domain/magentorc_05/web/vendor/shardj/zf1-future/library/Zend/Locale/Format.php(387): Zend_Locale_Math_PhpMath::Sub('0', '', 0)
#1 /home/wwwroot/lnmp01/domain/magentorc_05/web/vendor/shardj/zf1-future/library/Zend/Locale/Format.php(666): Zend_Locale_Format::toNumber('', Array)
#2 /home/wwwroot/lnmp01/domain/magentorc_05/web/vendor/shardj/zf1-future/library/Zend/Filter/NormalizedToLocalized.php(110): Zend_Locale_Format::toFloat('', Array)
#3 /home/wwwroot/lnmp01/domain/magentorc_05/web/lib/Varien/Data/Form/Filter/Date.php(72): Zend_Filter_NormalizedToLocalized->filter('')
#4 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Eav/Model/Attribute/Data/Abstract.php(191): Varien_Data_Form_Filter_Date->inputFilter('')
#5 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Eav/Model/Attribute/Data/Date.php(34): Mage_Eav_Model_Attribute_Data_Abstract->_applyInputFilter('')
#6 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Eav/Model/Form.php(355): Mage_Eav_Model_Attribute_Data_Date->extractValue(Object(Mage_Core_Controller_Request_Http))
#7 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Adminhtml/controllers/CustomerController.php(623): Mage_Eav_Model_Form->extractData(Object(Mage_Core_Controller_Request_Http), 'account')
#8 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/local/Mage/Core/Controller/Varien/Action.php(422): Mage_Adminhtml_CustomerController->validateAction()
#9 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(256): Mage_Core_Controller_Varien_Action->dispatch('validate')
#10 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Core/Controller/Varien/Front.php(182): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 /home/wwwroot/lnmp01/domain/magentorc_05/web/app/Mage.php(739): Mage_Core_Model_App->run(Array)
#13 /home/wwwroot/lnmp01/domain/magentorc_05/web/index.php(72): Mage::run('', 'store')
#14 {main}
  thrown in /home/wwwroot/lnmp01/domain/magentorc_05/web/vendor/shardj/zf1-future/library/Zend/Locale/Math/PhpMath.php on line 97
```````````````````````````````
After click Save Customer button,it will be redirect dashbord,the ajax request status is 500.

**Comment by fballiano** [comment]
I think it was already solved because I can't reproduce it on our "main" branch

**Comment by TangLiang** [comment]
@fballiano what's should we do if we still want to keep use the OpenMage 20.1.0-rc3?

**Comment by TangLiang** [comment]
@fballiano Awesome,thank you sooo....much!

**Comment by TangLiang** [comment]
@fballiano 
thanks for your reply,after debug,i found the problem in the file.

```````````````````````````````````
Mage_Eav_Model_Attribute_Data_Abstract

protected function _applyInputFilter($value)
    {
        if ($value === false) {
            return false;
        }

        $filter = $this->_getFormFilter();
        if ($filter) {
            $value = $filter->inputFilter($value);
        }

        return $value;
    }

````````````````````````````````````````````````````

As you can see,if the $value is empty like '' it will not return false,so the error comes.After change it to !$value in if,it's works,no errors and can add or edit customer on backend.
```````````````````````````````````````
protected function _applyInputFilter($value)
    {
        if (!$value) {
            return false;
        }

        $filter = $this->_getFormFilter();
        if ($filter) {
            $value = $filter->inputFilter($value);
        }

        return $value;
    }
```````````````````````````````````````````````````
But i am not sure is this a bug or php version problem.
I'm runing on nginx 1.20,php PHP 8.2.4

**Comment by TangLiang** [comment]
Debug in this file
Mage_Eav_Model_Attribute_Data_Date
`````````````````````````````````
public function extractValue(Zend_Controller_Request_Http $request)
    {
        $value = $this->_getRequestValue($request);
        Mage::log(gettype($value));
        return $this->_applyInputFilter($value);
    }
````````````````````````````````````````````````````
The system log file show the $value is string
```````````````````````````````````````````````````````````````````````````
2023-05-16T16:45:37+00:00 DEBUG (7): string

**Comment by kiatng** [comment]
I also cannot replicate the error. @TangLiang Can you try updating the dependencies: `composer update`

**Comment by ADDISON74** [comment]
DDEV (Apache, PHP 8.2.3, MariaDB), OpenMage 20.1.0-rc4 the latest without Sample Data (git clone. ddev config, ddev openmage-admin, composer update). I was able to create a customer account for both types **Main Website** and **Admin**. Screenshots attached. There are no files in /var/log.

![website](https://github.com/OpenMage/magento-lts/assets/8360474/258c549c-ef8a-4290-be44-b9b97a70cb86)

![admin](https://github.com/OpenMage/magento-lts/assets/8360474/e05d4c63-63fd-41d0-ae1e-5e02bfbfe04b)

**Comment by TangLiang** [comment]
yes,after composer update,the error message gone.with fresh database.but with old dateabase it's still the same,i think it's not bug.

but from the code 

```````````````````````````````````````````````````
/**
     * Apply attribute input filter to value
     *
     * @param string $value
     * @return false|string
     */
    protected function _applyInputFilter($value)
    {
        if ($value === false) {
            return false;
        }

        $filter = $this->_getFormFilter();
        if ($filter) {
            $value = $filter->inputFilter($value);
        }

        return $value;
    }
````````````````````````````````````````````````````````````````````
the $value type should be string right?

**Comment by ADDISON74** [comment]
PHPStan does a very good job. If there are any issue it will report them. Also, the log files can reveal possible errors and warnings. I don't see anything wrong in that method.

**Comment by fballiano** [comment]
I've created https://github.com/OpenMage/magento-lts/pull/3268 for this problem, although I don't think there's anything bad in the core code, we can see that some of these methods have wrong signatures which may lead to these problems.
