### ISSUE TITLE
Bug: source model adminhtml/system_config_source_cms_wysiwyg_skin is not found

### ISSUE THREAD

**Issue by pquerner** [OpenMage/magento-lts#3519]
### Steps to reproduce (*)

1. Clean install e19862bd0ee32be2b5e8ad4760cfb444fc6655a3
2. Install and goto admin system configuration > content management

### Expected result (*)

1. No errors

### Actual result (*)

1. Errors with `source model adminhtml/system_config_source_cms_wysiwyg_skin is not found`

```
a:5:{i:0;s:75:"Source model 'adminhtml/system_config_source_cms_wysiwyg_skin' is not found";i:1;s:1572:"#0 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(423): Mage::throwException('Source model 'a...')
#1 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(196): Mage_Adminhtml_Block_System_Config_Form->initFields(Object(Varien_Data_Form_Element_Fieldset), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#2 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Form.php(131): Mage_Adminhtml_Block_System_Config_Form->_initGroup(Object(Varien_Data_Form), Object(Mage_Core_Model_Config_Element), Object(Mage_Core_Model_Config_Element))
#3 /var/www/html/app/code/core/Mage/Adminhtml/Block/System/Config/Edit.php(91): Mage_Adminhtml_Block_System_Config_Form->initForm()
#4 /var/www/html/app/code/core/Mage/Adminhtml/controllers/System/ConfigController.php(107): Mage_Adminhtml_Block_System_Config_Edit->initForm()
#5 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(421): Mage_Adminhtml_System_ConfigController->editAction()
#6 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch('edit')
#7 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(181): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 /var/www/html/app/code/core/Mage/Core/Model/App.php(358): Mage_Core_Controller_Varien_Front->dispatch()
#9 /var/www/html/app/Mage.php(743): Mage_Core_Model_App->run(Array)
#10 /var/www/html/index.php(60): Mage::run('', 'store')
#11 {main}";s:3:"url";s:85:"/index.php/admin/system_config/edit/section/cms/key/6ff2e8969fde9ebdd437adea70e76a78/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}
```

**Comment by pquerner** [comment]
nvm, it was some outdated setting / cache.
