### ISSUE TITLE
PHP 8.1 TypeError: imagecopymerge(): Argument #9 ($pct) must be of type int in GD when custom watermark image is applied

### ISSUE THREAD

**Issue by Tomasz-Silpion** [OpenMage/magento-lts#3727]
### Preconditions (*)

1. PHP 8.1 or newer.
2. Main branch or any recent version of OpenMage.

### Steps to reproduce (*)

1. Go to System -> Configuration -> Product Image Watermarks.
2. Add watermark images and set every opacity field to any value.

### Expected result (*)

Watermark is properly applied to the product image.

### Actual result (*)

TypeError: imagecopymerge(): Argument #9 ($pct) must be of type int, string given exception is thrown in lib/Varien/Image/Adapter/Gd2.php:504

**Comment by kiatng** [comment]
I had the exact same thing [a week ago](https://makandracards.com/magento1/614548-uncaught-typeerror-imagecopymerge-argument-9-pct-must-be-of-type-int-string-given-in-lib-varien-image-adapter-gd2-php-570):

Uncaught TypeError: imagecopymerge(): Argument #9 ($pct) must be of type int, string given in .../lib/Varien/Image/Adapter/Gd2.php:570
Posted 7 days ago. Visible to the public. Linked content.
Uncaught TypeError: imagecopymerge(): Argument #9 ($pct) must be of type int, string given in /.../lib/Varien/Image/Adapter/Gd2.php:570
Stack trace:
#0 /.../lib/Varien/Image/Adapter/Gd2.php(570): imagecopymerge(Object(GdImage), Object(GdImage), 0, 0, 0, 0, 400, 400, '')
#1 /.../lib/Varien/Image.php(197): Varien_Image_Adapter_Gd2->watermark('/home/web/publi...', 0, 0, 30, false)
#2 /.../app/code/core/Mage/Catalog/Model/Product/Image.php(557): Varien_Image->watermark('/home/web/publi...')
#3 /.../app/code/core/Mage/Catalog/Helper/Image.php(362): Mage_Catalog_Model_Product_Image->setWatermark('default/images_...')
#4 /.../app/design/frontend/.../default/template/page/html/head.phtml(73): Mage_Catalog_Helper_Image->__toString()

Set the product watermark opacity to some integer value:

**Comment by sreichel** [comment]
@all-contributors add @Tomasz-Silpion bug
