### ISSUE TITLE
Deprecated functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3796]
**OpenMage 20.3
PHP 8.3
Magento Sample Pack
MAGE_IS_DEVELOPER_MODE=1**

johndoe@example.com has 3 products in his cart. Log into this account then go to the shopping cart. Once you press the [Proceed to Checkout] button you will get this error:

```php
Deprecated functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated  in /var/www/html/app/code/core/Mage/GiftMessage/Block/Message/Inline.php on line 245

#0 [internal function]: mageCoreErrorHandler()
#1 /var/www/html/app/code/core/Mage/GiftMessage/Block/Message/Inline.php(245): trim()
#2 /var/www/html/app/design/frontend/base/default/template/giftmessage/inline.phtml(115): Mage_GiftMessage_Block_Message_Inline->getEscaped()
#3 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#4 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#5 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#6 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Template->_toHtml()
#7 /var/www/html/app/code/core/Mage/GiftMessage/Helper/Message.php(87): Mage_Core_Block_Abstract->toHtml()
#8 /var/www/html/app/design/frontend/base/default/template/checkout/onepage/shipping_method/additional.phtml(17): Mage_GiftMessage_Helper_Message->getInline()
#9 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#10 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#11 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#12 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Template->_toHtml()
#13 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Abstract->toHtml()
#14 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(587): Mage_Core_Block_Abstract->_getChildHtml()
#15 /var/www/html/app/design/frontend/base/default/template/checkout/onepage/shipping_method.phtml(26): Mage_Core_Block_Abstract->getChildHtml()
#16 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#17 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#18 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#19 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Template->_toHtml()
#20 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Abstract->toHtml()
#21 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(587): Mage_Core_Block_Abstract->_getChildHtml()
#22 /var/www/html/app/design/frontend/rwd/default/template/checkout/onepage.phtml(37): Mage_Core_Block_Abstract->getChildHtml()
#23 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#24 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#25 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#26 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Template->_toHtml()
#27 /var/www/html/app/code/core/Mage/Core/Block/Text/List.php(35): Mage_Core_Block_Abstract->toHtml()
#28 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Text_List->_toHtml()
#29 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Abstract->toHtml()
#30 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(587): Mage_Core_Block_Abstract->_getChildHtml()
#31 /var/www/html/app/design/frontend/rwd/default/template/page/2columns-right.phtml(37): Mage_Core_Block_Abstract->getChildHtml()
#32 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#33 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#34 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#35 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Template->_toHtml()
#36 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(573): Mage_Core_Block_Abstract->toHtml()
#37 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#38 /var/www/html/app/code/core/Mage/Checkout/controllers/OnepageController.php(204): Mage_Core_Controller_Varien_Action->renderLayout()
#39 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(421): Mage_Checkout_OnepageController->indexAction()
#40 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch()
#41 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(181): Mage_Core_Controller_Varien_Router_Standard->match()
#42 /var/www/html/app/code/core/Mage/Core/Model/App.php(358): Mage_Core_Controller_Varien_Front->dispatch()
#43 /var/www/html/app/Mage.php(760): Mage_Core_Model_App->run()
#44 /var/www/html/index.php(56): Mage::run()
#45 {main}
```
**IMPORTANT**
If we do not make an effort to check all the code automatically or manually we will have big surprises, some parts will not work with the newest versions of PHP.

**Comment by ADDISON74** [comment]
We missed this deprecation in the code. Here is the fix for it:

https://onlinephp.io/c/54a59

**Comment by ADDISON74** [comment]
File: /app/code/core/Mage/GiftMessage/Block/Message/Inline.php on line 246.

```php
    /**
     * Return escaped value
     *
     * @param string $value
     * @param string $defaultValue
     * @return string
     */
    public function getEscaped($value, $defaultValue = '')
    {
        return $this->escapeHtml(trim($value) != '' ? $value : $defaultValue);
    }
```

How would you like to proceed for this part of the code to fix this issue?

**VARIANT 1**

```php
    public function getEscaped($value, $defaultValue = '')
    {
        $value = $value ?? '';
        return $this->escapeHtml(trim($value) != '' ? $value : $defaultValue);
    }
```

**VARIANT 2**

```php
    public function getEscaped($value, $defaultValue = '')
    {
        return $this->escapeHtml(trim($value ?? '') != '' ? $value : $defaultValue);
    }
```

**VARIANT 3**

```php
    public function getEscaped($value, $defaultValue = '')
    {
        return $this->escapeHtml((string) trim($value) != '' ? $value : $defaultValue);
    }
```

**VARIANT 4**
```php
    public function getEscaped($value, $defaultValue = '')
    {
        return $this->escapeHtml((empty($value) ? '' : trim($value)) != '' ? $value : $defaultValue);
    }
```

**VARIANT 5**
```php
    public function getEscaped($value, $defaultValue = '')
    {
        if (is_string($value)) {
            return $this->escapeHtml(trim($value) != '' ? $value : $defaultValue);
        }
    }
```

All the variants above solve the issue. Any feedback is welcome.

**Comment by fballiano** [comment]
I'd do this:

```php
public function getEscaped($value, $defaultValue = '')
{
    if ($value === null || strlen($value) == 0) return $defaultValue;
    return $this->escapeHtml(trim($value));
}
```
it seems to me easier to read and should give a tiny fraction more performance because it doesn't call functions that are not needed with an empty string.

PS: I think variant 5 doesn't work because it never returns the $defaultvalue for an empty $value

**Comment by ADDISON74** [comment]
Your version is fine too. It is good to discuss before proposing a PR. such a change must take into account the non-alteration of performance, the ease of reading the code.

I would use { } with the condition, as if this has been done before (I am remembering well).

```php
public function getEscaped($value, $defaultValue = '')
{
    if ($value === null || strlen($value) == 0) {
        return $defaultValue;
    }
    return $this->escapeHtml(trim($value));
}
```

**To Be Discussed**
1. I searched the OpenMage code for the following string **escapeHtml(trim($**. I found a few more, but I didn't investigate further. Do you think we should change in different PR's those as a preventive measure?
2. Such errors could not be automatically identified in the source code of a workflow?

**Comment by fballiano** [comment]
right about the brakets, phpcs would have complained ehhehe

1. nice idea, I think it could also be one single PR, expecially if it's not many places to fix
2. I don't know enough about this but probably PHPStan with a "higher level" configuration would detect those (among many many other errors) but we couldn't raise the level because of the many errors it triggers...
