### ISSUE TITLE
Fatal error:  Uncaught Error: Call to a member function setOnclick() on false

### ISSUE THREAD

**Issue by ADDISON74** [OpenMage/magento-lts#3814]
OpenMage 20.3.0
Magento Sample Pack
PHP 8.3
MAGE_IS_DEVELOPER_MODE=1

**Steps to reproduce this issue**

1 - Go to the **Backend > Sales > Orders**
2 - Click on any row in the Order grid

**You will get this error**

```php
Fatal error:  Uncaught Error: Call to a member function setOnclick() on false in /var/www/html/app/code/core/Mage/Adminhtml/Block/Sales/Order/View/Giftmessage.php:91
Stack trace:
#0 /var/www/html/app/design/adminhtml/default/default/template/sales/order/view/giftmessage.phtml(40): Mage_Adminhtml_Block_Sales_Order_View_Giftmessage->getSaveButtonHtml()
#1 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#2 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#3 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#4 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(67): Mage_Core_Block_Template->_toHtml()
#5 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Adminhtml_Block_Template->_toHtml()
#6 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Abstract->toHtml()
#7 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(583): Mage_Core_Block_Abstract->_getChildHtml()
#8 /var/www/html/app/design/adminhtml/default/default/template/sales/order/giftoptions.phtml(16): Mage_Core_Block_Abstract->getChildHtml()
#9 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#10 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#11 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#12 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(67): Mage_Core_Block_Template->_toHtml()
#13 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Adminhtml_Block_Template->_toHtml()
#14 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Abstract->toHtml()
#15 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(587): Mage_Core_Block_Abstract->_getChildHtml()
#16 /var/www/html/app/code/core/Mage/Adminhtml/Block/Sales/Order/View/Tab/Info.php(93): Mage_Core_Block_Abstract->getChildHtml()
#17 /var/www/html/app/design/adminhtml/default/default/template/sales/order/view/tab/info.phtml(77): Mage_Adminhtml_Block_Sales_Order_View_Tab_Info->getGiftOptionsHtml()
#18 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#19 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#20 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#21 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(67): Mage_Core_Block_Template->_toHtml()
#22 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Adminhtml_Block_Template->_toHtml()
#23 /var/www/html/app/code/core/Mage/Adminhtml/Block/Widget/Tabs.php(392): Mage_Core_Block_Abstract->toHtml()
#24 /var/www/html/app/design/adminhtml/default/default/template/widget/tabs.phtml(32): Mage_Adminhtml_Block_Widget_Tabs->getTabContent()
#25 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#26 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#27 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#28 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(67): Mage_Core_Block_Template->_toHtml()
#29 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Adminhtml_Block_Template->_toHtml()
#30 /var/www/html/app/code/core/Mage/Core/Block/Text/List.php(35): Mage_Core_Block_Abstract->toHtml()
#31 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Core_Block_Text_List->_toHtml()
#32 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(643): Mage_Core_Block_Abstract->toHtml()
#33 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(587): Mage_Core_Block_Abstract->_getChildHtml()
#34 /var/www/html/app/design/adminhtml/default/default/template/page.phtml(47): Mage_Core_Block_Abstract->getChildHtml()
#35 /var/www/html/app/code/core/Mage/Core/Block/Template.php(273): include('...')
#36 /var/www/html/app/code/core/Mage/Core/Block/Template.php(310): Mage_Core_Block_Template->fetchView()
#37 /var/www/html/app/code/core/Mage/Core/Block/Template.php(323): Mage_Core_Block_Template->renderView()
#38 /var/www/html/app/code/core/Mage/Adminhtml/Block/Template.php(67): Mage_Core_Block_Template->_toHtml()
#39 /var/www/html/app/code/core/Mage/Core/Block/Abstract.php(926): Mage_Adminhtml_Block_Template->_toHtml()
#40 /var/www/html/app/code/core/Mage/Core/Model/Layout.php(573): Mage_Core_Block_Abstract->toHtml()
#41 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(390): Mage_Core_Model_Layout->getOutput()
#42 /var/www/html/app/code/core/Mage/Adminhtml/controllers/Sales/OrderController.php(115): Mage_Core_Controller_Varien_Action->renderLayout()
#43 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Action.php(421): Mage_Adminhtml_Sales_OrderController->viewAction()
#44 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(255): Mage_Core_Controller_Varien_Action->dispatch()
#45 /var/www/html/app/code/core/Mage/Core/Controller/Varien/Front.php(181): Mage_Core_Controller_Varien_Router_Standard->match()
#46 /var/www/html/app/code/core/Mage/Core/Model/App.php(358): Mage_Core_Controller_Varien_Front->dispatch()
#47 /var/www/html/app/Mage.php(760): Mage_Core_Model_App->run()
#48 /var/www/html/index.php(56): Mage::run()
#49 {main}
  thrown in /var/www/html/app/code/core/Mage/Adminhtml/Block/Sales/Order/View/Giftmessage.php on line 91
```

This is the PHP file and the line:

/app/code/core/Mage/Adminhtml/Block/Sales/Order/View/Giftmessage.php:91

**Comment by kiatng** [comment]
I am not sure how to replicate this, I have enabled gift messages, I checkout a product with gift message, but I cannot see the gift message in backend order page.
![image](https://github.com/OpenMage/magento-lts/assets/1106470/a3c46318-4d70-4a3e-8d13-1f49686a0a99)

Any idea what I am missing?

**Comment by ADDISON74** [comment]
It is OpenMage 20.3.0 cloned and updated. I am using the Magento Sample Pack to get data and simulate almost everything. Debian 12 + PHP 8.3. There are no other changes, I didn't change any setting in the Backend. 

Please try to use the same environment conditions mentioned in the first post. I will investigate more in detail.

**Comment by ADDISON74** [comment]
This proves the error based on the configuration mentioned in the initial post

https://github.com/OpenMage/magento-lts/assets/8360474/9e4ae32f-4f77-43a1-a5f9-01fa55e42e5d
