### ISSUE TITLE
PHP Error in frontend with improper request params

### ISSUE THREAD

**Issue by ioweb-gr** [OpenMage/magento-lts#3925]
### Preconditions (*)
1. Openmage 20.5.0

### Steps to reproduce (*)
1. Visit url https://demo.openmage.org/men/shirts.html?occasion=30,31 and check the php error

### Expected result (*)
1. The page opens and the filter is not applied but do not show error to the user. 

### Actual result (*)
1. PHP Error 

```
 Uncaught TypeError: strlen(): Argument #1 ($string) must be of type string, array given in /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Catalog/Model/Layer/Filter/Attribute.php:81\nStack trace:\n#0 /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Catalog/Block/Layer/Filter/Abstract.php(81): Mage_Catalog_Model_Layer_Filter_Attribute->apply()\n#1 /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Catalog/Block/Layer/Filter/Abstract.php(63): Mage_Catalog_Block_Layer_Filter_Abstract->_initFilter()\n#2 /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Catalog/Block/Layer/View.php(125): Mage_Catalog_Block_Layer_Filter_Abstract->init()\n#3 /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Core/Block/Abstract.php(299): Mage_Catalog_Block_Layer_View->_prepareLayout()\n#4 /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Core/Model/Layout.php(474): Mage_Core_Block_Abstract->setLayout()\n#5 /var/www/vhosts/example.gr/httpdocs/app/code/core/Mage/Core/M.
```

**Comment by fballiano** [comment]
I've created https://github.com/OpenMage/magento-lts/pull/3926 to fix this, please review the PR when you can

**Comment by ioweb-gr** [comment]
Thanks I'll be able to test it tomorrow
