### ISSUE TITLE
Paypal IPN seems broken/not supported

### ISSUE THREAD

**Issue by seansan** [OpenMage/magento-lts#477]
We are receiving the following messages since some time using M1938. We have setup paypal express.

paypal express works without IPN enabled
and breaks when we enable IPN : payments are never completed

--------------

Please check your server that handles PayPal Instant Payment Notifications (IPN). IPNs sent to the following URL(s) are failing:

https://example.com/paypal/ipn/

If you do not recognize this URL, you may be using a service provider that is using IPN on your behalf. Please contact your service provider with the above information. If this problem continues, IPNs may be disabled for your account.

```
Exception: Reply from PayPal does not contain required parameters. in app/code/core/Mage/Paypal/Model/Api/Nvp.php:996
Stack trace:
#0 app/code/core/Mage/Paypal/Model/Api/Nvp.php(644): Mage_Paypal_Model_Api_Nvp->call('DoExpressChecko...', Array)
#1 app/code/core/Mage/Paypal/Model/Express.php(581): Mage_Paypal_Model_Api_Nvp->callDoExpressCheckoutPayment()
#2 app/code/core/Mage/Paypal/Model/Express.php(377): Mage_Paypal_Model_Express->_placeOrder(Object(Mage_Sales_Model_Order_Payment), '99')
#3 app/code/core/Mage/Sales/Model/Order/Payment.php(443): Mage_Paypal_Model_Express->capture(Object(Mage_Sales_Model_Order_Payment), '99')
#4 app/code/core/Mage/Sales/Model/Order/Invoice.php(395): Mage_Sales_Model_Order_Payment->capture(Object(Mage_Sales_Model_Order_Invoice))
#5 app/code/core/Mage/Sales/Model/Order/Payment.php(608): Mage_Sales_Model_Order_Invoice->capture()
#6 app/code/core/Mage/Sales/Model/Order/Payment.php(410): Mage_Sales_Model_Order_Payment->_invoice()
#7 app/code/core/Mage/Sales/Model/Order/Payment.php(348): Mage_Sales_Model_Order_Payment->capture(NULL)
#8 app/code/core/Mage/Sales/Model/Order.php(896): Mage_Sales_Model_Order_Payment->place()
#9 app/code/core/Mage/Sales/Model/Order.php(1114): Mage_Sales_Model_Order->_placePayment()
#10 app/code/core/Mage/Core/Model/Resource/Transaction.php(105): Mage_Sales_Model_Order->place()
#11 app/code/core/Mage/Core/Model/Resource/Transaction.php(159): Mage_Core_Model_Resource_Transaction->_runCallbacks()
#12 app/code/core/Mage/Sales/Model/Service/Quote.php(189): Mage_Core_Model_Resource_Transaction->save()
#13 app/code/core/Mage/Sales/Model/Service/Quote.php(249): Mage_Sales_Model_Service_Quote->submitOrder()
#14 app/code/core/Mage/Paypal/Model/Express/Checkout.php(600): Mage_Sales_Model_Service_Quote->submitAll()
#15 app/code/core/Mage/Paypal/Controller/Express/Abstract.php(320): Mage_Paypal_Model_Express_Checkout->place('EC-2NW91927EX23...')
#16 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Paypal_Controller_Express_Abstract->placeOrderAction()
#17 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('placeOrder')
#18 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#19 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#2```

References:
(does not work for us)

https://support.weltpixel.com/hc/en-us/articles/115006119347-How-to-fix-PayPal-Instant-Payment-Notification-IPN-Warning-SOLVED-

https://magento.stackexchange.com/questions/25695/magento-1-8-1-not-receiving-paypal-ipn

Related issue in M2? https://github.com/magento/magento2/issues/2878

Seems same issue: https://magento.stackexchange.com/questions/12584/paypal-ipn-not-triggering-order-status-updates

**Comment by fabianus76** [comment]
same Problem here - thanks for any feedback how you got it fixed !

**Comment by seansan** [comment]
Not sure, too long ago

There is a fix here
https://github.com/OpenMage/magento-lts/pull/194#pullrequestreview-244615646

And I remember we needed to go into Paypal and click some things there?
Also maybe something in nginx config

**Comment by luigifab** [comment]
Iit can be closed?

**Comment by sreichel** [comment]
IMHO yes. We got the same email two weeks ago with M2 and PayPal extension installed.
